name: Deploy to Azure App Service
on:
  push:
    branches:
      - main

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
  SSL_MODE: ${{ secrets.SSL_MODE }}
  JWT_KEY: ${{ secrets.JWT_KEY }}
  JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
  JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
  JWT_EXPIRATION_HOURS: ${{ secrets.JWT_EXPIRATION_HOURS }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish --no-build

      - name: Login to Azure
        uses: azure/login@v1

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./publish"
